use std::env;
use std::fs;
use std::path::PathBuf;
use std::process;

use schemars::schema::RootSchema;
use typify::{TypeSpace, TypeSpaceSettings};

const HEADER: &str = "// This file is generated by `bun run --filter '@disbot/shared' generate:rust-types`.\n// Do not edit by hand. Regenerate after changing Zod schemas in packages/shared/src/dsl.\n\n#![allow(clippy::all)]\n#![allow(dead_code)]\n\n";

fn main() {
    let args: Vec<String> = env::args().collect();
    let mut input: Option<PathBuf> = None;
    let mut output: Option<PathBuf> = None;
    let mut iter = args.iter().skip(1);
    while let Some(arg) = iter.next() {
        match arg.as_str() {
            "--input" => input = iter.next().map(PathBuf::from),
            "--output" => output = iter.next().map(PathBuf::from),
            other => {
                eprintln!("unknown argument: {other}");
                process::exit(2);
            }
        }
    }

    let input = input.unwrap_or_else(|| die("--input <path-to-json-schema> is required"));
    let output = output.unwrap_or_else(|| die("--output <path-to-rust-file> is required"));

    let schema_text = fs::read_to_string(&input)
        .unwrap_or_else(|e| die(&format!("failed to read input {input:?}: {e}")));
    let schema: RootSchema = serde_json::from_str(&schema_text)
        .unwrap_or_else(|e| die(&format!("failed to parse JSON Schema: {e}")));

    let mut settings = TypeSpaceSettings::default();
    settings.with_struct_builder(false);
    let mut type_space = TypeSpace::new(&settings);
    type_space
        .add_root_schema(schema)
        .unwrap_or_else(|e| die(&format!("typify failed: {e}")));

    let body = prettyplease::unparse(
        &syn::parse2::<syn::File>(type_space.to_stream())
            .unwrap_or_else(|e| die(&format!("failed to parse generated tokens: {e}"))),
    );

    let mut contents = String::with_capacity(HEADER.len() + body.len());
    contents.push_str(HEADER);
    contents.push_str(&body);

    fs::write(&output, contents)
        .unwrap_or_else(|e| die(&format!("failed to write output {output:?}: {e}")));
}

fn die(msg: &str) -> ! {
    eprintln!("disbot-codegen: {msg}");
    process::exit(1);
}
