// This file is generated by `bun run --filter '@disbot/shared' generate:rust-types`.
// Do not edit by hand. Regenerate after changing Zod schemas in packages/shared/src/dsl.

#![allow(clippy::all)]
#![allow(dead_code)]

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
///`BotConfig`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "BotConfig",
///  "type": "object",
///  "required": [
///    "triggers"
///  ],
///  "properties": {
///    "triggers": {
///      "type": "array",
///      "items": {
///        "title": "MessageCreateTrigger",
///        "type": "object",
///        "required": [
///          "actions",
///          "event"
///        ],
///        "properties": {
///          "actions": {
///            "type": "array",
///            "items": {
///              "title": "SendMessageAction",
///              "type": "object",
///              "required": [
///                "content",
///                "type"
///              ],
///              "properties": {
///                "content": {
///                  "type": "string"
///                },
///                "on_error": {
///                  "default": "stop",
///                  "type": "string",
///                  "enum": [
///                    "stop",
///                    "continue"
///                  ]
///                },
///                "type": {
///                  "type": "string",
///                  "enum": [
///                    "send_message"
///                  ]
///                }
///              }
///            }
///          },
///          "event": {
///            "type": "string",
///            "enum": [
///              "message_create"
///            ]
///          }
///        }
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct BotConfig {
    pub triggers: ::std::vec::Vec<MessageCreateTrigger>,
}
impl ::std::convert::From<&BotConfig> for BotConfig {
    fn from(value: &BotConfig) -> Self {
        value.clone()
    }
}
///`MessageCreateTrigger`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "MessageCreateTrigger",
///  "type": "object",
///  "required": [
///    "actions",
///    "event"
///  ],
///  "properties": {
///    "actions": {
///      "type": "array",
///      "items": {
///        "title": "SendMessageAction",
///        "type": "object",
///        "required": [
///          "content",
///          "type"
///        ],
///        "properties": {
///          "content": {
///            "type": "string"
///          },
///          "on_error": {
///            "default": "stop",
///            "type": "string",
///            "enum": [
///              "stop",
///              "continue"
///            ]
///          },
///          "type": {
///            "type": "string",
///            "enum": [
///              "send_message"
///            ]
///          }
///        }
///      }
///    },
///    "event": {
///      "type": "string",
///      "enum": [
///        "message_create"
///      ]
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct MessageCreateTrigger {
    pub actions: ::std::vec::Vec<SendMessageAction>,
    pub event: MessageCreateTriggerEvent,
}
impl ::std::convert::From<&MessageCreateTrigger> for MessageCreateTrigger {
    fn from(value: &MessageCreateTrigger) -> Self {
        value.clone()
    }
}
///`MessageCreateTriggerEvent`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "string",
///  "enum": [
///    "message_create"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum MessageCreateTriggerEvent {
    #[serde(rename = "message_create")]
    MessageCreate,
}
impl ::std::convert::From<&Self> for MessageCreateTriggerEvent {
    fn from(value: &MessageCreateTriggerEvent) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for MessageCreateTriggerEvent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::MessageCreate => f.write_str("message_create"),
        }
    }
}
impl ::std::str::FromStr for MessageCreateTriggerEvent {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "message_create" => Ok(Self::MessageCreate),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for MessageCreateTriggerEvent {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for MessageCreateTriggerEvent {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for MessageCreateTriggerEvent {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`SendMessageAction`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "SendMessageAction",
///  "type": "object",
///  "required": [
///    "content",
///    "type"
///  ],
///  "properties": {
///    "content": {
///      "type": "string"
///    },
///    "on_error": {
///      "default": "stop",
///      "type": "string",
///      "enum": [
///        "stop",
///        "continue"
///      ]
///    },
///    "type": {
///      "type": "string",
///      "enum": [
///        "send_message"
///      ]
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct SendMessageAction {
    pub content: ::std::string::String,
    #[serde(default = "defaults::send_message_action_on_error")]
    pub on_error: SendMessageActionOnError,
    #[serde(rename = "type")]
    pub type_: SendMessageActionType,
}
impl ::std::convert::From<&SendMessageAction> for SendMessageAction {
    fn from(value: &SendMessageAction) -> Self {
        value.clone()
    }
}
///`SendMessageActionOnError`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "default": "stop",
///  "type": "string",
///  "enum": [
///    "stop",
///    "continue"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum SendMessageActionOnError {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "continue")]
    Continue,
}
impl ::std::convert::From<&Self> for SendMessageActionOnError {
    fn from(value: &SendMessageActionOnError) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for SendMessageActionOnError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Stop => f.write_str("stop"),
            Self::Continue => f.write_str("continue"),
        }
    }
}
impl ::std::str::FromStr for SendMessageActionOnError {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "stop" => Ok(Self::Stop),
            "continue" => Ok(Self::Continue),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for SendMessageActionOnError {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for SendMessageActionOnError {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SendMessageActionOnError {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::default::Default for SendMessageActionOnError {
    fn default() -> Self {
        SendMessageActionOnError::Stop
    }
}
///`SendMessageActionType`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "string",
///  "enum": [
///    "send_message"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum SendMessageActionType {
    #[serde(rename = "send_message")]
    SendMessage,
}
impl ::std::convert::From<&Self> for SendMessageActionType {
    fn from(value: &SendMessageActionType) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for SendMessageActionType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::SendMessage => f.write_str("send_message"),
        }
    }
}
impl ::std::str::FromStr for SendMessageActionType {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "send_message" => Ok(Self::SendMessage),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for SendMessageActionType {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for SendMessageActionType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SendMessageActionType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
/// Generation of default values for serde.
pub mod defaults {
    pub(super) fn send_message_action_on_error() -> super::SendMessageActionOnError {
        super::SendMessageActionOnError::Stop
    }
}
